services:
  sqlserver:
    image: 'mcr.microsoft.com/mssql/server:latest'
    container_name: MSSQLServer
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_PID: 'Developer'
      MSSQL_DB: ${MSSQL_DB}
      MSSQL_USER: ${MSSQL_USER}
      MSSQL_PASSWORD: ${MSSQL_PASSWORD}
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    ports:
      - '1433:1433'
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data: